const japaneseContent = {
  ui: {
    skipLink: "本文へ移動",
    brandHome: "Jinnosuke Kamimura のトップへ",
    navLabel: "メインナビゲーション",
    profileSnapshot: "プロフィール概要",
    currentPosition: "現在の所属",
    affiliation: "所属",
    profileNote: "研究、エンジニアリング、\nその間にある問い。",
    heroEyebrow: "研究者ポートフォリオ · 東京、日本",
    theme: {
      darkAction: "ダークテーマに切り替える",
      lightAction: "明るいテーマに切り替える",
      darkMode: "ダークモード",
      lightMode: "ライトモード",
    },
    language: {
      toEnglish: "英語に切り替える",
      toJapanese: "日本語に切り替える",
    },
    nav: {
      about: "About me",
      research: "Research",
      papers: "Papers & Awards",
      publications: "Publications",
      awards: "Awards",
      projects: "Projects",
      experience: "Experience",
      contact: "Contact",
    },
    research: {
      heading: "Research interests",
      description: "",
      empty: "研究テーマは準備中です。確認できた内容から順次追加します。",
    },
    publications: {
      heading: "Papers",
      internationalHeading: "International conferences",
      domesticHeading: "Domestic conferences",
      journalsHeading: "Journals",
      description: "",
      featuredEmpty: "代表的な研究業績は準備中です。",
      empty: "業績一覧は、確認できた情報から追加します。",
    },
    awards: {
      heading: "Awards",
      description: "",
      empty: "受賞歴は準備中です。",
      badge: "Award",
      titleSeparator: "　",
      issuedBy: "発行元",
      themeLabel: "テーマ：",
      sourceLink: "Source",
    },
    fellowships: {
      heading: "Fellowship",
      description: "",
      empty: "フェローシップ情報は準備中です。",
    },
    projects: {
      heading: "Projects",
      description: "研究や実装のプロジェクトを、成果物へのリンクとともに紹介します。",
      empty: "プロジェクトは準備中です。",
    },
    experience: {
      heading: "Experience & education",
      description: "",
      empty: "経歴は準備中です。",
    },
    contact: {
      heading: "Let’s connect.",
      lead: "研究、共同プロジェクト、技術についての連絡先をここにまとめます。",
      empty: "メールアドレスや外部プロフィールは、登録後に表示されます。",
    },
    footer: {
      backToTop: "トップへ戻る",
    },
    meta: {
      title: "Jinnosuke Kamimura | 研究者ポートフォリオ",
      description: "Jinnosuke Kamimura の研究者ポートフォリオ",
    },
    noscript: "追加情報を表示するには JavaScript を有効にしてください。",
  },
  profile: {
    name: "Jinnosuke Kamimura",
    role: "博士課程1年",
    positionLabel: "博士課程1年",
    affiliation: "東京大学大学院情報理工学系研究科",
    department: "システム情報学専攻",
    lab: "川嶋研究室",
    labUrl: "https://www.bmc.ipc.i.u-tokyo.ac.jp/index.html",
    email: "5158231060kj [at] g.ecc.u-tokyo.ac.jp",
    location: "東京, 日本",
    summary: "医療現場における術者の負担軽減を目的とした、空気圧制御を基盤とする手術支援ロボットの自律制御を研究しています。",
  },
  researchThemes: [
    { index: "01", title: "Surgical Robotics" },
    { index: "02", title: "Pneumatic Control" },
    { index: "03", title: "Physical AI" },
  ],
  internationalConferences: [
    {
      year: "2026年",
      venue: "2026 IEEE/SICE International Symposium on System Integration (SII)",
      title: "Human-in-the-Loop Control of a Soft Pneumatic Exosuit for Step Width Guidance via Hip Abduction/Adduction.",
      authors: "Jinnosuke Kamimura, Tetsuro Miyazaki, Kenji Kawashima",
      citation: "2026 IEEE/SICE International Symposium on System Integration (SII), pp. 358–363, 2026.",
      links: [
        { label: "DOI", href: "https://doi.org/10.1109/SII64115.2026.11404503" },
        { label: "researchmap", href: "https://researchmap.jp/jinnosuke-kamimura/published_papers/53727628" },
      ],
    },
    {
      year: "2024年",
      venue: "Lecture Notes in Mechanical Engineering",
      title: "Study on Accident-Avoidance Mechanism in Driver-Vehicle System When Activating Level-2 ADAS",
      authors: "Norika Arai, Jinnosuke Kamimura, Yohei Fujinami, Xingguo Zhang, Pongsathorn Raksincharoensak, Masaaki Uechi, Shintaro Inoue, Fumio Sugaya, Kazunori Nogi, Toshinori Okita",
      citation: "Lecture Notes in Mechanical Engineering, pp. 137–143, 2024 (Presented at AVEC 2024).",
      links: [
        { label: "DOI", href: "https://doi.org/10.1007/978-3-031-70392-8_20" },
        { label: "researchmap", href: "https://researchmap.jp/jinnosuke-kamimura/published_papers/53727635" },
      ],
    },
  ],
  domesticConferences: [
    {
      year: "To appear",
      venue: "第35回日本コンピュータ外科学会大会",
      title: "空気圧駆動鉗子による推定把持力を用いた把持・牽引動作の模倣学習",
      authors: "上村仁之介，高杉颯汰，長ヶ部拓吾，川嶋健嗣",
      citation: "第35回日本コンピュータ外科学会大会，to appear．",
    },
    {
      year: "2025年",
      venue: "日本フルードパワーシステム学会春季講演会",
      title: "内転・外転を含む股関節・膝関節運動の支援を目的とした空気圧ゴム人工筋スーツの設計とその評価",
      authors: "上村仁之介，宮嵜哲郎，川嶋健嗣",
      citation: "日本フルードパワーシステム学会春季講演会，2025．",
      links: [
        { label: "J-GLOBAL", href: "https://jglobal.jst.go.jp/detail?JGLOBAL_ID=202502289683849228" },
        { label: "researchmap", href: "https://researchmap.jp/jinnosuke-kamimura/misc/53727614" },
      ],
    },
    {
      year: "2025年",
      venue: "計測自動制御学会産業応用部門大会",
      title: "空気圧型ソフトエクソスーツを用いた歩隔誘導のためのヒューマンインザループ制御の検証",
      authors: "上村仁之介，宮嵜哲郎，川嶋健嗣",
      citation: "計測自動制御学会産業応用部門大会，2025．",
    },
    {
      year: "2024年",
      venue: "LIFE2024",
      title: "空気圧人工筋スーツを用いた両脚力覚教示の評価",
      authors: "上村仁之介，宮嵜哲郎，沼田深匡，宮川翔太，川嶋健嗣",
      citation: "LIFE2024，2024．",
      links: [
        { label: "J-GLOBAL", href: "https://jglobal.jst.go.jp/detail?JGLOBAL_ID=202502262296906408" },
        { label: "researchmap", href: "https://researchmap.jp/jinnosuke-kamimura/misc/53727615" },
      ],
    },
  ],
  journals: [
    {
      year: "2026",
      venue: "Sensors and Materials",
      title: "Examining Step-width Guidance Using a Soft Pneumatic Exosuit via Hip Abduction/Adduction Assistance",
      authors: "Jinnosuke Kamimura, Yuri Mikawa, Tetsuro Miyazaki, Kenji Kawashima",
      citation: "Sensors and Materials, 2026.",
    },
  ],
  fellowships: [
    {
      year: "2026年9月",
      issuer: "日本学術振興会",
      title: "特別研究員−DC2（採用内定）",
      detailLabel: "プロジェクト名：",
      detail: "ヒト感覚運動制御に学ぶ空気圧駆動鉗子を用いた手術支援ロボットの軟組織把持自律制御",
    },
  ],
  awards: [
    {
      year: "2025年11月",
      issuer: "公益社団法人 計測自動制御学会（SICE）産業応用部門",
      title: "流体計測制御シンポジウム ベストプレゼンテーション賞",
      detailLabel: "対象論文：",
      detail: "空気圧型ソフトエクソスーツを用いた歩隔誘導のためのヒューマンインザループ制御の検証",
      source: "https://www.sice.or.jp/ia-div/best_presentation_shou.html",
    },
    {
      year: "2024年9月",
      issuer: "第7回データサイエンスコンテスト",
      title: "優秀賞",
      theme: "就職活動における学生の負担軽減と適職マッチングのための教示あり学習モデルの構築と評価",
      detailLabel: "テーマ：",
      detail: "第7回データサイエンスコンテスト。チーム「はちみつ干し梅」のメンバーとして受賞。",
      source: "https://www.mi.u-tokyo.ac.jp/contest2024.html",
    },
  ],
  projects: [],
  timeline: [
    {
      period: "2026–now",
      title: "博士課程1年",
      organization: "東京大学・大学院情報理工学系研究科・システム情報学専攻",
      detail: "",
    },
    {
      period: "2024–2026",
      title: "修士(情報理工学)修了",
      organization: "東京大学・大学院情報理工学系研究科・システム情報学専攻",
      detail: "",
    },
    {
      period: "2020–2024",
      title: "学士(工学)修了",
      organization: "東京農工大学・工学部・機械システム工学科",
      detail: "",
    },
    {
      period: "2016–2019",
      title: "高等学校卒業",
      organization: "川越東高等学校",
      detail: "",
    },
  ],
};

const englishContent = {
  ui: {
    skipLink: "Skip to content",
    brandHome: "Back to Jinnosuke Kamimura's top",
    navLabel: "Main navigation",
    profileSnapshot: "Profile snapshot",
    currentPosition: "Current position",
    affiliation: "Affiliation",
    profileNote: "Research, engineering,\nand the questions between them.",
    heroEyebrow: "Research portfolio · Tokyo, Japan",
    theme: {
      darkAction: "Switch to dark theme",
      lightAction: "Switch to light theme",
      darkMode: "Dark mode",
      lightMode: "Light mode",
    },
    language: {
      toEnglish: "Switch to English",
      toJapanese: "Switch to Japanese",
    },
    nav: {
      about: "About me",
      research: "Research",
      papers: "Papers & Awards",
      publications: "Publications",
      awards: "Awards",
      projects: "Projects",
      experience: "Experience",
      contact: "Contact",
    },
    research: {
      heading: "Research interests",
      description: "",
      empty: "Research topics are being prepared and will be added as details are confirmed.",
    },
    publications: {
      heading: "Papers",
      internationalHeading: "International conferences",
      domesticHeading: "Domestic conferences",
      journalsHeading: "Journals",
      description: "",
      featuredEmpty: "Selected research outputs are being prepared.",
      empty: "The publication list will be updated with confirmed information.",
    },
    awards: {
      heading: "Awards",
      description: "",
      empty: "Awards are being prepared.",
      badge: "Award",
      titleSeparator: " · ",
      issuedBy: "Issued by",
      themeLabel: "Theme:",
      sourceLink: "Official source",
    },
    fellowships: {
      heading: "Fellowship",
      description: "",
      empty: "Fellowship information is being prepared.",
    },
    projects: {
      heading: "Projects",
      description: "Research and engineering projects will be introduced with links to their outputs.",
      empty: "Projects are being prepared.",
    },
    experience: {
      heading: "Experience & education",
      description: "",
      empty: "Experience is being prepared.",
    },
    contact: {
      heading: "Let’s connect.",
      lead: "Contact information for research, collaborations, and technology will be collected here.",
      empty: "Email and external profiles will appear here once they are registered.",
    },
    footer: {
      backToTop: "Back to top",
    },
    meta: {
      title: "Jinnosuke Kamimura | Research Portfolio",
      description: "Research portfolio of Jinnosuke Kamimura",
    },
    noscript: "Please enable JavaScript to display additional information.",
  },
  profile: {
    name: "Jinnosuke Kamimura",
    role: "First-Year Doctoral Student",
    positionLabel: "First-Year Doctoral Student",
    affiliation: "Graduate School of Information Science and Technology, The University of Tokyo",
    department: "Department of Systems Information Science",
    lab: "Kawashima Laboratory",
    labUrl: "https://www.bmc.ipc.i.u-tokyo.ac.jp/index.html",
    email: "5158231060kj [at] g.ecc.u-tokyo.ac.jp",
    location: "Tokyo, Japan",
    summary: "I research autonomous control of surgical robots based on pneumatic control to reduce the burden on surgeons in clinical settings.",
  },
  researchThemes: [
    { index: "01", title: "Surgical Robotics" },
    { index: "02", title: "Pneumatic Control" },
    { index: "03", title: "Physical AI" },
  ],
  internationalConferences: [
    {
      year: "2026",
      venue: "2026 IEEE/SICE International Symposium on System Integration (SII)",
      title: "Human-in-the-Loop Control of a Soft Pneumatic Exosuit for Step Width Guidance via Hip Abduction/Adduction.",
      authors: "Jinnosuke Kamimura, Tetsuro Miyazaki, Kenji Kawashima",
      citation: "2026 IEEE/SICE International Symposium on System Integration (SII), pp. 358–363, 2026.",
      links: [
        { label: "DOI", href: "https://doi.org/10.1109/SII64115.2026.11404503" },
        { label: "researchmap", href: "https://researchmap.jp/jinnosuke-kamimura/published_papers/53727628" },
      ],
    },
    {
      year: "2024",
      venue: "Lecture Notes in Mechanical Engineering",
      title: "Study on Accident-Avoidance Mechanism in Driver-Vehicle System When Activating Level-2 ADAS",
      authors: "Norika Arai, Jinnosuke Kamimura, Yohei Fujinami, Xingguo Zhang, Pongsathorn Raksincharoensak, Masaaki Uechi, Shintaro Inoue, Fumio Sugaya, Kazunori Nogi, Toshinori Okita",
      citation: "Lecture Notes in Mechanical Engineering, pp. 137–143, 2024 (Presented at AVEC 2024).",
      links: [
        { label: "DOI", href: "https://doi.org/10.1007/978-3-031-70392-8_20" },
        { label: "researchmap", href: "https://researchmap.jp/jinnosuke-kamimura/published_papers/53727635" },
      ],
    },
  ],
  domesticConferences: [
    {
      year: "To appear",
      venue: "第35回日本コンピュータ外科学会大会",
      title: "空気圧駆動鉗子による推定把持力を用いた把持・牽引動作の模倣学習",
      authors: "上村仁之介，高杉颯汰，長ヶ部拓吾，川嶋健嗣",
      citation: "第35回日本コンピュータ外科学会大会，to appear．",
    },
    {
      year: "2025",
      venue: "日本フルードパワーシステム学会春季講演会",
      title: "内転・外転を含む股関節・膝関節運動の支援を目的とした空気圧ゴム人工筋スーツの設計とその評価",
      authors: "上村仁之介，宮嵜哲郎，川嶋健嗣",
      citation: "日本フルードパワーシステム学会春季講演会，2025．",
      links: [
        { label: "J-GLOBAL", href: "https://jglobal.jst.go.jp/detail?JGLOBAL_ID=202502289683849228" },
        { label: "researchmap", href: "https://researchmap.jp/jinnosuke-kamimura/misc/53727614" },
      ],
    },
    {
      year: "2025",
      venue: "計測自動制御学会産業応用部門大会",
      title: "空気圧型ソフトエクソスーツを用いた歩隔誘導のためのヒューマンインザループ制御の検証",
      authors: "上村仁之介，宮嵜哲郎，川嶋健嗣",
      citation: "計測自動制御学会産業応用部門大会，2025．",
    },
    {
      year: "2024",
      venue: "LIFE2024",
      title: "空気圧人工筋スーツを用いた両脚力覚教示の評価",
      authors: "上村仁之介，宮嵜哲郎，沼田深匡，宮川翔太，川嶋健嗣",
      citation: "LIFE2024，2024．",
      links: [
        { label: "J-GLOBAL", href: "https://jglobal.jst.go.jp/detail?JGLOBAL_ID=202502262296906408" },
        { label: "researchmap", href: "https://researchmap.jp/jinnosuke-kamimura/misc/53727615" },
      ],
    },
  ],
  journals: [
    {
      year: "2026",
      venue: "Sensors and Materials",
      title: "Examining Step-width Guidance Using a Soft Pneumatic Exosuit via Hip Abduction/Adduction Assistance",
      authors: "Jinnosuke Kamimura, Yuri Mikawa, Tetsuro Miyazaki, Kenji Kawashima",
      citation: "Sensors and Materials, 2026.",
    },
  ],
  fellowships: [
    {
      year: "Sep 2026",
      issuer: "Japan Society for the Promotion of Science (JSPS)",
      title: "Research Fellow−DC2 (Provisional Selection)",
      detailLabel: "Project:",
      detail: "ヒト感覚運動制御に学ぶ空気圧駆動鉗子を用いた手術支援ロボットの軟組織把持自律制御",
    },
  ],
  awards: [
    {
      year: "Nov 2025",
      issuer: "The Society of Instrument and Control Engineers (SICE), Industrial Applications Division",
      title: "Fluid Measurement and Control Symposium Best Presentation Award",
      detailLabel: "Target paper:",
      detail: "Verification of human-in-the-loop control for stride-width guidance using a pneumatic soft exosuit.",
      source: "https://www.sice.or.jp/ia-div/best_presentation_shou.html",
    },
    {
      year: "Sep 2024",
      issuer: "7th Data Science Contest",
      title: "Excellence Award",
      theme: "Building and evaluating a supervised learning model to reduce the burden of job hunting and improve job matching.",
      detailLabel: "Theme:",
      detail: "Awarded as a member of the team “Hachimitsu Boshi-Ume” in the 7th Data Science Contest.",
      source: "https://www.mi.u-tokyo.ac.jp/contest2024.html",
    },
  ],
  projects: [],
  timeline: [
    {
      period: "2026–now",
      title: "First-Year Doctoral Student",
      organization: "The University of Tokyo · Graduate School of Information Science and Technology · Department of Systems Information Science",
      detail: "",
    },
    {
      period: "2024–2026",
      title: "Master of Information Science and Technology",
      organization: "The University of Tokyo · Graduate School of Information Science and Technology · Department of Systems Information Science",
      detail: "",
    },
    {
      period: "2020–2024",
      title: "Bachelor of Engineering",
      organization: "Tokyo University of Agriculture and Technology · Faculty of Engineering · Department of Mechanical Systems Engineering",
      detail: "",
    },
    {
      period: "2016–2019",
      title: "High School Graduate",
      organization: "Kawagoe Higashi High School",
      detail: "",
    },
  ],
};

window.siteContent = {
  defaultLanguage: "ja",
  languageOptions: [
    { code: "ja", label: "日本語" },
    { code: "en", label: "English" },
  ],
  languages: {
    ja: japaneseContent,
    en: englishContent,
  },
  links: [
    {
      label: "LinkedIn",
      href: "https://www.linkedin.com/in/jinnosuke-kamimura-935934416/",
    },
    {
      label: "researchmap",
      href: "https://researchmap.jp/jinnosuke-kamimura",
    },
    {
      label: "ORCID",
      href: "https://orcid.org/0009-0003-8860-4377",
    },
  ],
  ...japaneseContent,
};
